libraries:
  REPLACE_WITH_AUDIOBOOK_LIBRARY_NAME:
    collection_files:
      - file: config/audiobooks.yml
    operations:
      delete_collections:
        managed: true
        configured: false
        less: 1

plex:
  url: REPLACE_WITH_LOCAL_PLEX_URL
  token: REPLACE_WITH_PLEX_TOKEN

tmdb:
  apikey: REPLACE_WITH_TMDB_API_KEY
